# Defines the development configuration for docker-compose.
version: '2'

services:

  frontend:
    build: ./frontend
    # restart: always
    expose:
    - "3000"
    ports:
      - "3000:3000"
    volumes:
      # mount local working directory for development
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    command: ["bash", "-c", "yarn install && webpack-dev-server"]
